/**
 * Class Entry:
 *
 * This class defines a person (dead or alive) and its properties
 *
 * author: Anuj More (atm140330)
 */

package ui.killemall.model;

import android.location.Location;
import java.io.File;

public class Entry {

    private File file;
    private String timestamp;
    private Location location;
    private EntryStatus status;

    /**
     * Constructors for Entry objects
     */
    public Entry() {}

    public Entry(File file, String timestamp, Location location) {
        this.file = file;
        this.timestamp = timestamp;
        this.location = location;
        this.status = EntryStatus.ALIVE;
    }

    public Entry(File file, String timestamp, Location location, EntryStatus status) {
        this.file = file;
        this.timestamp = timestamp;
        this.location = location;
        this.status = status;
    }

    @Override
    public String toString() {
        final String separator = "::";

        String locationString = null;
        if (location != null) {
            locationString = Double.toString(location.getLongitude())
                    + separator + Double.toString(location.getLatitude());
        } else {
            locationString = "0.0" + separator + "0.0";
            System.out.println("FAILED LOCATION IS NULL");
        }

        return (file.getAbsolutePath() + separator +
                timestamp + separator +
                locationString + separator +
                status.toString());
    }

    public void deleteImage() {
        file.delete();
    }

    /*
     * Autogenerated code ahead
     * Don't read
     *
     * Getters and setters
     */
    public File getFile() {
        return file;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public Location getLocation() {
        return location;
    }

    public EntryStatus getStatus() {
        return status;
    }

    public String getDate() {
        return getTimestamp().split("--")[0];
    }

    public String getTime() {
        return getTimestamp().split("--")[1];
    }

    public String getLongitude() {
        return Double.toString(getLocation().getLongitude());
    }

    public String getLatitude() {
        return Double.toString(getLocation().getLatitude());
    }

    public void setStatus(EntryStatus status) {
        this.status = status;
    }
}
