package ui.killemall.model;

import android.location.Location;
import java.io.File;

public class Entry {

    private File file;
    private String timestamp;
    private Location location;
    private EntryStatus status;

    /**
     * Constructors for Entry objects
     */
    public Entry() {}

    public Entry(File file, String timestamp, Location location) {
        this.file = file;
        this.timestamp = timestamp;
        this.location = location;
        this.status = EntryStatus.ALIVE;
    }

    public Entry(File file, String timestamp, Location location, EntryStatus status) {
        this.file = file;
        this.timestamp = timestamp;
        this.location = location;
        this.status = status;
    }

    @Override
    public String toString() {
        final String separator = "::";
        return (file.getAbsolutePath() + separator +
                timestamp + separator +
                /*
                Double.toString(location.getLongitude()) + separator +
                Double.toString(location.getLongitude()) + separator +
                */
                "0.0" + separator +
                "0.0" + separator +
                status.toString());
    }

    /*
     * Autogenerated code ahead
     * Don't read
     *
     * Getters
     */
    public File getFile() {
        return file;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public Location getLocation() {
        return location;
    }

    public EntryStatus getStatus() {
        return status;
    }


}
